[main]
serverDebug: true
useDatabase: true
staticPath: ../web

server-host: 0.0.0.0
server-port: 3000

mysql-credential-name: mysql
mysql-credential-pw: groot321123
mysql-database-name: Data
mysql-database-host: 127.0.0.1

dataFile: ../DataIn.txt
newDataQueryFile: ../DataNew.txt