[main]
serverDebug: true
useDatabase: false
staticPath: ../web

server-host: 0.0.0.0
server-port: 3000

mysql-credential-name: ''
mysql-credential-pw: 
mysql-database-name: 
mysql-database-host: 

dataFile: ../Liste.txt
dataFileEncoding: utf8
newDataQueryFile: ../DataNew.txt